I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script call
    call medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 48, in script call
    call magazine(2)
  File "game/script.rpy", line 29, in script call
    call medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 48, in script call
    call magazine(2)
ScriptError: could not find label 'magazine'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script call
    call medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 48, in script call
    call magazine(2)
  File "renpy/ast.py", line 1490, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 29, in script call
    call medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 48, in script call
    call magazine(2)
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'magazine'.

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
 1.0
Sun Mar 27 15:54:43 2022
