I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script call
    call medic from _call_medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 6, in script call
    call scene_0001 from _call_scene_0001
  File "game/scripts/scenes/psychiatrist/scene-0001.rpy", line 34, in script
    menu:
KeyError: u'paciente'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script call
    call medic from _call_medic
  File "game/scripts/miscellaneous/psychiatrist.rpy", line 6, in script call
    call scene_0001 from _call_scene_0001
  File "game/scripts/scenes/psychiatrist/scene-0001.rpy", line 34, in script
    menu:
  File "renpy/ast.py", line 1684, in execute
    renpy.exports.say(None, "\n".join(narration), interact=False)
  File "renpy/exports.py", line 1419, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1236, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "renpy/character.py", line 1155, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "renpy/character.py", line 1135, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'paciente'

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
EMPATHY 0.5
Thu May 19 23:47:54 2022
